### PR TITLE
Fix setting transparent color

### PR DESCRIPTION
**Pull request by heikkipora**
Index calculation findClosest() produced fractional indices to this.usedEntry[], fixed that.

### CODE REVIEW

**Comment by heikkipora** [comment]
After the initial fix transparency calculation was working quite randomly. This is because there can be multiple entries in the indexed palette with the same value -> transIndex points to one of them, but not necessarily the same one is used in the image data itsel.

As a solution I forced all pixels that have 0xff as alpha value in the 32bit source images to use the transIndex.

**Comment by kryo2k** [comment]
Also having a problem with transparency using this library. Tried out your patch, but only the first frame went transparent. Also, the wrong color was set to transparent. Not sure what I need to send to .setTransparent(..?) but the background color of each frame is white, and I am sending '#ffffff'.

**Comment by heikkipora** [comment]
For me it works nicely when the background color is set to 0xffffff00 (pixel format is RGBA) and .setTransparent(0xffffff)

**Comment by kryo2k** [comment]
Hm, can I ask how you're setting the background color?

I am using the following implementation:

    var
    GIFEncoder = require('gifencoder'),
    Canvas = require('canvas'),
    fs = require('fs');

    module.exports = function (filePath, str, cb) {

      var
      WIDTH   = 100, HEIGHT = 30,
      encoder = new GIFEncoder(WIDTH, HEIGHT),
      ws      = fs.createWriteStream(filePath);

      ws.on('error', function (err) { cb(err); });
      ws.on('finish', function () { cb(null, filePath); });

      encoder.createReadStream().pipe(ws);

      encoder.start();

      encoder.setRepeat(-1);
      encoder.setDelay(1000);
      encoder.setQuality(10);
      encoder.setTransparent('#ffffff');

      var
      ctx = (new Canvas(WIDTH, HEIGHT)).getContext('2d');

      ctx.fillStyle = '#ffffff';
      ctx.fillRect(0, 0, WIDTH, HEIGHT);

      ctx.font         = '20px "Impact"';
      ctx.textAlign    = 'center';
      ctx.textBaseline = 'middle';
      ctx.fillStyle    = '#000000';
      ctx.fillText(str, WIDTH / 2, HEIGHT / 2, WIDTH);

      encoder.addFrame(ctx);

      process.nextTick(function () { // ensure async
        encoder.finish();
      });
    };

Which when called, produces an image like:
image
*The white background should be transparent, the red border is just to show that it is not.*

I have tried several other combinations of background fill styles, and none seem to work. When I do:

    ctx.fillStyle = 0xffffff00; // or 'rgba(255,255,255,0)' or '#ffffff00'
    ctx.fillRect(0, 0, WIDTH, HEIGHT);

The background is completely black, regardless to what I set for a value of setTransparent(...).

When I applied your patch, the black font went transparent and the background remained completely opaque. Greatly appreciate any help. Been fighting with this for a couple days.

**Comment by heikkipora** [comment]
I use GIFEncoder directly on data that was read from a PNG file and processed byte-by-byte.
Take a look at [fmi-radar-images.js](https://github.com/heikkipora/sataako-fi/blob/master/src/fmi-radar-images.js)

When I wrote the patch my project was producing multi-frame GIFs but at the moment I only have a single frame / GIF file. I try to find time to take a look at your code more closely. Maybe Canvas is doing something unexpected behind the scenes to the pixel data.

**Comment by heikkipora** [comment]
I noticed you have a string value as the parameter in encoder.setTransparent('#ffffff') - which it does not expect. Use a numeric value instead (0xffffff) and see if that fixes the issue for you.

**Comment by kryo2k** [comment]
Hello again,  I tried
    encoder.setTransparent(0xffffff);
    ctx.fillStyle = '#ffffff';
    ctx.fillRect(0, 0, WIDTH, HEIGHT);

But the white background remains in the encoded image.

**Comment by slasktrat** [comment]
+1 for this fix! It works like a charm

**Comment by twolfson** [comment]
As a heads up, @scinos came up with a more elegant solution in https://github.com/twolfson/gif-encoder/pull/7

It's to remove `findClosest` entirely (as we don't use it except for transparent images) and use the same `NeuQuant` lookup from a few lines before (as the color resolution should be the same since it was indexed)

**Comment by francoislg** [comment]
Any idea when this fix will be merged...?

**Comment by eugeneware** [comment]
Hi @heikkipora - thanks so much for the PR. I missed this PR! Sorry! I'm giving you commit access to this repo to in the spirit of http://openopensource.org/

If you let me know your npm user name I'll give you npm publish rights as well. 

Thanks again!

**Comment by heikkipora** [comment]
Thank you, sir! :) My NPM username is the same as the GitHub one.

**Pull request merged**
